.GlobalEnv
is.environment(.GlobalEnv)

source("/Users/jorge/Documents/R/Linaje/scripts/rutas_de_trabajo.R")
source(paste0(rutaconexiones,"/librerias.R"))
source(paste0(rutaconexiones,"/conexiones.R"))



#SQL---- 

INSERT /*+ PARALLEL(8) */ INTO USBGODA.GDVSQLTO SELECT  /*+ PARALLEL(8) */ SYS.GV_$SQL.* FROM SYS.GV_$SQL
WHERE SQL_ID NOT IN (SELECT SQL_ID FROM USBGODA.GD_V$SQL) ;

#AREA SQL ---- 
CREATE TABLE USBGODA.GDSQLATO AS (SELECT * FROM SYS.GV_$SQLAREA WHERE 1=2);
INSERT /*+ PARALLEL(8) */ INTO USBGODA.GDSQLATO SELECT  /*+ PARALLEL(8) */   SYS.GV_$SQLAREA.* FROM SYS.GV_$SQLAREA;

COMMIT;
#PLAN EJECUCION SQL ---- 

CREATE TABLE USBGODA.GDPLANTO AS (SELECT * FROM SYS.GV_$SQL_PLAN WHERE 1=2);

INSERT /*+ PARALLEL(8) */ 	INTO USBGODA.GDPLANTO     SELECT  /*+ PARALLEL(8) */ SYS.GV_$SQL_PLAN.* FROM SYS.GV_$SQL_PLAN

;
commit;
#STATS SQL ---- 
CREATE TABLE USBGODA.GDSTATTO AS (SELECT * FROM SYS.GV_$SQLSTATS WHERE 1=2);

INSERT /*+ PARALLEL(8) */ 	INTO USBGODA.GDSTATTO     SELECT  /*+ PARALLEL(8) */ SYS.GV_$SQLSTATS.* FROM SYS.GV_$SQLSTATS;
commit;
#SQL---- 
DROP TABLE USBGODA.GDSQLVTO PURGE;
CREATE TABLE USBGODA.GDSQLVTO AS (SELECT * FROM SYS.GV_$SQL WHERE 1=2);
INSERT /*+ PARALLEL(8) */  INTO USBGODA.GDSQLVTO   SELECT  /*+ PARALLEL(8) */ SYS.GV_$SQL.* FROM SYS.GV_$SQL
#SQL TEXTO---- 
DROP TABLE USBGODA.GDSQLTTO PURGE;
CREATE TABLE GDSQLTTO as (
  SELECT        *     FROM         GV_$SQLTEXT );
#VIEWS----
CREATE TABLE USBGODA.GDVIEWHO (VIEW VARCHAR2(30) Not Null,OWNER VARCHAR2(30) Not Null,VIEW_NAME VARCHAR2(30) Not Null,SQLTEXT CLOB,FX_INICIO DATE FORMAT(DD/MM/YYYY),FX_FIN DATE FORMAT(DD/MM/YYYY));
TRUNCATE TABLE USBGODA.GDVIEWTO;
INSERT INTO USBGODA.GDVIEWTO(select u.name||'.'||o.name,u.name, o.name, to_LOB(v.text), SYSDATE FORMAT(DD/MM/YYYY)
                             FROM
                             sys."_CURRENT_EDITION_OBJ" o, sys.view$ v, sys.user$ u
                             where o.obj# = v.obj#
                             and o.owner# = u.user#);
                             
INSERT INTO USBGODA.GDVIEWHO SELECT USBGODA.GDVIEWTO.*,(31/12/2500)(DATE)  FROM USBGODA.GDVIEWTO WHERE VIEW IN (
SELECT VIEW FROM USBGODA.GDVIEWTO MINUS SELECT VIEW FROM USBGODA.GDVIEWHO);

UPDATE TABLE USBGODA.GDVIEWHO FX_FIN=SYSDATE-1 (DATE)   WHERE VIEW IN (
  SELECT VIEW FROM USBGODA.GDVIEWTO MINUS SELECT VIEW FROM USBGODA.GDVIEWHO);

UPDATE TABLE USBGODA.GDVIEWHO USBGODA.GDVIEWHO.SQLTEXT=USBGODA.GDVIEWTO.SQLTEXT
WHERE VIEW IN (
  SELECT VIEW FROM USBGODA.GDVIEWTO INTERSECION SELECT VIEW FROM USBGODA.GDVIEWHO);


INSERT INTO USBGODA.GDSQLTTO AS
  SELECT SQL_ID, TEXTO FROM(
    Select SQL_ID,  LOWER(TO_CLOB(SQL_FULLTEXT)) as "CSQL_TEXT",
    REGEXP_REPLACE(TO_CLOB("CSQL_TEXT"),'((--)(.*?)$)|(/\*(.*)[^\*/]\*/)|(\")|(;)','',1,0,'m') AS "SQL_TRATADO",
    REGEXP_REPLACE(TO_CLOB("SQL_TRATADO"),'(\s){1,}|(\s){1,}$|$',' ',1,0,'m')AS "SQL_TRATADO2",
    REGEXP_REPLACE(TO_CLOB("SQL_TRATADO2"),'^((\s){1,})|((\s){1,})$','',1,0,'m') AS "TEXTO"
    from USBGODA.GDSQLVTO) AS B;

commit;

select * from  USBGODA.GV_SQL



  #QERYTO PASO1----

              
  TRUNCATE TABLE USBGODA.GDQERYTO_TEMP2 ;
  alter table USBGODA.GDQERYTO_TEMP2 nologging;
  set autotrace on statistics
  insert into  USBGODA.GDQERYTO_TEMP2  SELECT  /*+ PARALLEL(8) */   
    SQL_ID,  
  SQL_FULLTEXT,
  REGEXP_REPLACE(LOWER(SQL_FULLTEXT),'((--)(.*?)$)|(/\*(.*)[^\*/]\*/){1,}|(\"){1,}|(;)','',1,0,'m') as "SQLTRATADO1" ,
  FIRST_LOAD_TIME,
  PARSING_SCHEMA_NAME,
  UPPER("SERVICE") AS "SERVICE",
  UPPER(MODULE) AS MODULE,
  ADDRESS,
  HASH_VALUE,
  PLAN_HASH_VALUE,
  --       ROW_NUMBER() OVER (PARTITION BY dbms_crypto.hash("SQLTRATADO1",2) order by 1) R
  (ROW_NUMBER() OVER (PARTITION BY SQL_ID order by 1)) AS REPETS
  FROM USBGODA.GDSQLVTO where SQL_ID not in (select SQL_ID from GDQERYIO);
  commit;
