## RUTAS DE TRABAJO  
setwd("/Users/jorge/Documents/R/Linaje")
setwd("/Users/jorge/Documents/R/Linaje/scripts/rutas_de_trabajo.R")
rutainicial <- getwd()
rutaoriginal<- paste0(rutainicial,"/DATOS")
rutadatos<- paste0(rutainicial,"/DATOS")
rutadatosentrada<- paste0(rutadatos,"/Entrada")
rutadatossalida<- paste0(rutadatos,"/Salida")
rutadatossistema<- paste0(rutadatos,"/Sistema")
rutascripts<-  paste0(rutainicial,"/scripts")
rutasqls<-  paste0(rutascripts,"/SQLs")
rutaconexiones<-  paste0(rutascripts,"/conexiones")
rutajdbc<-paste0(rutascripts,"/jdbc")
rutavignettes<-paste0(rutainicial,"/vignettes")
rutaapp<- paste0(rutainicial,"/app/Linaje")
