select CO_QUERY,REGEXP_REPLACE("SQL_TRATADO",'(\s){1,}|(\s){1,}$|$',' ',1,0,'m') as "SQL",USERNAME from 
(
select CO_QUERY,
REGEXP_REPLACE(DS_QUERY,'((--)(.*?)$)|(/\*(.*)[^\*/]\*/)|(\")|(;)','',1,0,'m') as "SQL_TRATADO",CO_BBDD_DEFECTO as "USERNAME"
 
from  JAGP_DWGDQUTT
where
it_ini_consulta(date, format 'yyyy-MM-dd') >= '2020-09-30' (date,format 'yyyy-MM-dd') 
and DS_GRUPO_SENTENCIAS like 'DML%'

) as T1; 

REGEXP_REPLACE(DS_QUERY,'((--)(.*?)$)|(/\*(.*)[^\*/]\*/)|(\")|(;)','',1,0,'m') as "SQL_TRATADO"


     
     


CREATE VOLATILE TABLE VOLATIL_T1,,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO  
(
CO_QUERY DECIMAL(18,0),
DS_QUERY VARCHAR(31000) CHARACTER SET UNICODE NOT CASESPECIFIC,
CO_BBDD_DEFECTO VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('VIEWPOINT','DWGROVP0','TFUSECP0','DWGRCVP0','DWGR2VP0','T146989','D9GRMVP0','DWGRAVP0','DWGRUVP0','BBDDTEMP_GDPR','T147795','D9GRGVP0','D9GRSVP0','DWSIEMP0','D9GRHVP0','DWBACOP0','DWBCPVP0','D9GRBTP0','DWGRCTP0','DWGRBVP0','D9USEOMV','PDCRINFO','S1BASEP0','C7GRAVP0','UT06093','DWGRMVP0','DWGRDVP0','DWGGOVP0','TEUSECP0','T147282','DWGRJVP0','DWGRBTP0','DWSHUTP0','D9GRIVP0','T136900','D9GROVP0','DWSEGUP0','DWUSEEMC','DWUSEXHI','QCD1','DWPMPYP0','DWGRWVP0','DWSALSP0','PDCRADMIN','DWPMBTP0','D9ESCAP0','DWGRPVP0','DWUSESGC','D9USERCC','DWUSPJP0','DWBCPTP0','USBTBLTE','C9GRAVP0','D9GRXVP0','DWUSERSC','D9GRFVP0','D9GRCVP0','TETBJOP0','PDCRDATA','DWUSERCO','UT04976','DWPR2VP0','SYS_CALENDAR','UT05840','TDGRBVP0','D9GRATP0','DWUSESP0','CRASHDUMPS','DWGREVP0','DWBOUTP0','TD_SYSXML','D9USETWG','SYSUDTLIB','SYSLIB','T132978','TDSTATS','TDCONSULTA','PDCRSTG','D9USERSC','DWESCVP0','D9GRDVP0','DWGRVVP0','T129970','DWOBCOP0','DWUSEFP6','DWUNUTP0','D9USERMM','DWRACVP0','D9GRNVP0','TDWM','DWUSEUTC','D9USEFP6','DWGRTVP0','DWGRZVP0','DWBASEP0','D9USETSM','DWUSEACC','D9USEREP','TDOPUTP0','DWTBJOP0','$NETVAULT_CATALOG','D9OPUTP0','TDQCD','CNSGNCP1','DWGRKVP0','DWUNUDP0','DWTURMP0','HADESLAS','D9UNUVP0','DWBACPP0','DWUSFOP0','PDCRADM','SQLJ','D9USEFLC','DWUSECIA','D9GRKVP0','D9USERGC','DWPMATP0','D9GRJVP0','DWOPUTP0','TD_SERVER_DB','TEBASEP0','T145934','D9USECP0','DWUSERF6','ADMPROD','DWUSERMA','D9GRBVP0','TEGRXVP0','D9GRAVP0','DWBDEXP0','CONSOLE','SYSSPATIAL','UT06121','DWUSERSG','D9GRRVP0','D9BCUTP0','DWCPUTP0','DWPRYVP0','DWSALTP0','D9USERST','DWUNUVP0','DWOBACP0','DWGRYVP0','DWUSEUGP','DWUBIBOX','DWGOBDP0','SYSTEMFE','DWGRSVP0','DWGR7VP0','D9GRQVP0','DWSPMCP0','DWBCTLP0','D9USERUC','D9GRPVP0','DWTBACP0','T147212','DWGRXVP0','CNGRXVP0','DWULISP0','DWGRIVP0','DWGRFVP0','DBCMNGR','DWPRODP0','D9USERTM','D9PREPP0','DWPROYP0','DWGRHVP0','SYSADMIN','D9GRWVP0','DBC','PRUEBA_TERADATA','DWESCAP0','DWRACTP0','D9USERTR','D9PRYVP0','DWGRATP0','DWGRNVP0','ADMUSERS','GRMONITO','DWECCAP0','DWGRLVP0','DWUSERWU','DWUSESCC','SYSUIF','DWGRRVP0','LOCKLOGSHREDDER','D9PROYP0','SYSBAR'),
 )PRIMARY INDEX ( CO_QUERY );